# Generated by Django 3.0.4 on 2024-06-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=100)),
                ('Education', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Recruitment', models.CharField(max_length=100)),
                ('No_Of_Trainings', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Previous_Year_Ratings', models.IntegerField()),
                ('Length_Of_Service', models.IntegerField()),
                ('Awards_Won', models.IntegerField()),
                ('Average_Trainings', models.IntegerField()),
                ('Employee_Promotion', models.IntegerField()),
            ],
        ),
    ]
